framework:
  secret: '%env(APP_SECRET)%'
  session: true

when@prod:
  framework:
    error_controller: App\Core\Controller\ErrorController::showErrorPage

when@dev:
  framework:
    error_controller: null

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file