image: atlassian/default-image:4

pipelines:
  default:
    - step:
        name: "PHP 8.4: Linting & Static Analysis"
        caches:
          - composer
        script:
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - composer run-script cs
          - composer run-script stan
        services:
          - docker
        php:
          - 8.4