Core:
  resource:
    path: ../src/Core/Controller/
    namespace: App\Core\Controller
  type: attribute
Application:
  resource:
    path: ../src/Application/Controller/
    namespace: App\Application\Controller
  type: attribute
Authentication:
  resource:
    path: ../src/Authentication/Controller/
    namespace: App\Authentication\Controller
  type: attribute